name: 'Honeybadger Deploy Action'
description: 'Send deployment notifications to the Honeybadger API'
inputs:
  api_key:
    description: 'The Honeybadger project API key'
    required: true
  environment:
    description: 'The deployment environment. Defaults to production.'
    required: false
    default: 'production'
  endpoint:
    description: 'The deploy submission endpoint. Only used for testing'
    required: true
    default: "https://api.honeybadger.io/v1/deploys"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.enviornment }}
    - ${{ inputs.endpoint }}
